### ISSUE TITLE
Configuring Good to log server.log() output

### ISSUE THREAD

**Issue by kokujin** [hapijs/good#294]
I would like the log output from my server to be picked up by good. At the moment, it only logs the default output.

````
	server.log(['hapi-waterline', 'info'],
					chalk.bold.blue(
						'Waterline connected and running'
					));
```

How do I get this to work? My present Good configuration options are. Thanks

````
var goodOptions = {
	opsInterval: 1000,
	reporters: [{
		reporter: require('good-console'),
		args: [{
			log: '*',
			response: '*'
		}]
	}, {
		reporter: require('good-file'),
		args: ['./logs/serverlog', {
			ops: '*'
		}]
	}, {
		reporter: require('good-http'),
		args: [{
			error: '*'
		}, 'http://prod.logs:3000', {
			threshold: 20,
			wreck: {
				headers: {
					'x-api-key': 12345
				}
			}
		}]
	}]
};
````

**Comment by AdriVanHoudt** [comment]
As far as I know the `log: '*'` option will catch the `server.log` log

**Comment by kokujin** [comment]
Sadly, it doesn't, is there anything else I need to configure,

**Comment by AdriVanHoudt** [comment]
Weird, I have this config
```json
"good": {
	"reporters": [{
		"reporter": "good-console",
		"args": [{
			"log": "*",
		}]
	}]
}
```

And I get logs like this: 
```
2015-01-16 | 11:18:17.035 , [log,start,server], data: Server running at: http://localhost:8000
```
While using
```
server.log(['start', 'server'], 'Server running at: ' + server.info.uri);
```

**Comment by AdriVanHoudt** [comment]
Maybe it's `chalk`?

**Comment by arb** [comment]
Yeah try just sending a string... I'm not sure what chalk is going to send through. If you want special formatting (like using chalk) you should just roll your own reporter.

**Comment by kokujin** [comment]
Thanks for the answers. 

I just did some tests, chalk is innocent.My logs are not committed to the log file. The only logs I see are:

````
{"event":"ops","timestamp":1421564925409,"host":"zeus","pid":12832,"os":{"load":[0.203125,0.24853515625,0.44287109375],"mem":{"total":3935105024,"free":666021888},"uptime":59494.825581085},"proc":{"uptime":2,"mem":{"rss":77750272,"heapTotal":69551104,"heapUsed":38561072},"delay":1.4812130006030202},"load":{"requests":{},"concurrents":{"3000":0},"responseTimes":{},"sockets":{"http":{"total":0},"https":{"total":0}}}}
{"event":"ops","timestamp":1421564926413,"host":"zeus","pid":12832,"os":{"load":[0.203125,0.24853515625,0.44287109375],"mem":{"total":3935105024,"free":667037696},"uptime":59495.829681784},"proc":{"uptime":3,"mem":{"rss":77787136,"heapTotal":69551104,"heapUsed":38637432},"delay":0.666660999879241},"load":{"requests":{},"concurrents":{"3000":0},"responseTimes":{},"sockets":{"http":{"total":0},"https":{"total":0}}}}
`````
Any other ideas? Thanks

**Comment by arb** [comment]
Based on your config, server events aren't going to go into your log file, only ops events. You'll need to add `log` into the event options of good file.

**Comment by AdriVanHoudt** [comment]
@arb But based on the first config he should see in console right?

**Comment by kokujin** [comment]
How is this then suppose to be configured @arb ? Code snippet?

**Comment by kokujin** [comment]
Nevermind, Iǜe got it now...

````
	reporter: require('good-file'),
		args: ['./logs/serverlog', {
			ops: '*',
			log: '*'
		}]
````

Thanks all
