### ISSUE TITLE
Rename Options

### ISSUE THREAD

**Issue by arb** [hapijs/good#299]
Rename `logRequestHeaders`, `logRequestPayload`, `logResponsePayload` because setting them only includes those values in the data passed into the different reporters and it creates confusion.

**Comment by shaunbruno** [comment]
Agreed. Ideally, the reporters could respect those options. Prior to seeing this I opened an issue under good-console:
https://github.com/hapijs/good-console/issues/36

Alternatively, those options could be per-reporter, which would give some flexibility as to how each interprets the options. But as it stands, the flags are misleading.
