### ISSUE TITLE
request-internal

### ISSUE THREAD

**Issue by briandela** [hapijs/good#302]
Is it possible to get some of the `request-internal` events from Good? For example, I'd like to write a good reporter that that logs like things

- request begins
- request payload
- any `request.log` calls
- response (with payload)

I can see how to get the `request.log` and reponse calls but I can't see how to get the request begins. I know I could write a logger which listens to the Hapi `request-internal` event myself but I'd like to make use of some of the other features of Good such as ops etc. and it would be nice to avoid having multiple loggers.

Apologies if I'm missing something. I looked through the good code and didn't see a way to write a reporter to get some of the `request-internal` events (specifically the request received is what I'm after)

Thoughts?

**Comment by arb** [comment]
No you can't do that yet. It's on the roadmap though.

**Comment by briandela** [comment]
@arb. Just wondering if this is still on the roadmap. What we're trying to achieve is essentially a logger which can log a request through it's life inside hapi. For example,

- log when the request begins (optionally log the request headers) (looks like this is the only thing we can't do with Good right now as `request-internal` events don't seem to be passed
- log all `request.log` calls
- log response details (i.e. end of request)

Just wondering if it's still on the roadmap or if we should look at building our own logging solution similar to Good.

**Comment by arb** [comment]
Please see the changes here: https://github.com/hapijs/good/issues/323

You can listen for `"request-internal"` via `extensions`

**Comment by briandela** [comment]
Thanks @arb. Missed that release.
