### ISSUE TITLE
Using good to log all console.log events?

### ISSUE THREAD

**Issue by bf** [hapijs/good#308]
I am unsure if I can use `good` as a general-purpose logger for anything that is written via console.log()  in a straightforward way. I can see that hooking `console.log` it is not the cleanest way to log stuff, but I have a legacy project at hand which needs step-by-step refactoring.

As the hapi `server` object is not exposed in all submodules of the project, I'd like to be able to log anything that happens into a file.

Any ideas on how to commence?

**Comment by AdriVanHoudt** [comment]
As far as I know Good can/will only log Hapi events.

**Comment by arb** [comment]
Good in intended to only log specific things coming out of a hapi server. You could try a different module like winston or bunyan if you want cross-cutting logging.
