### ISSUE TITLE
Log both tail and response

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/good#309]
Right now you can choose to either log on `response` or on `tail` which in itself is useful but it would be handy to be able to do both. 
The use case is to check if the response to the client is fast enough but still be able to log the amount of time it takes to finish the whole request. 
I don't think logging 2 times for both events would be useful so instead it would be something like  `logRequestHeaders` where you add additional info to the log.

**Comment by arb** [comment]
I feel like the amount of information available in the ops event is more than enough to determine response times. Plus logging both "response" AND "tail" would just make logs unreadable in the amount of information that was in them.
