### ISSUE TITLE
Clean Up Stop

### ISSUE THREAD

**Issue by arb** [hapijs/good#312]
Do we really need to remove the event handlers? The only time `stop` is called is when the hapi server emits the "stop" event and means the node process is probably about to end.

**Comment by Marsup** [comment]
Nope, it can happen multiple times in tests, and there's nothing preventing someone from spawning temporary servers for whatever reason.

**Comment by arb** [comment]
So we need to keep all that annoying logic to remove the event listeners? Why?

**Comment by Marsup** [comment]
Well you can probably keep them if you have zero chance to receive any. Did you ever make tests to see if losing any reference to a stopped hapi server GCs it ?
