### ISSUE TITLE
Be able to filter sensitive information 

### ISSUE THREAD

**Issue by danielb2** [hapijs/good#315]
Sensitive information like creditcard information or passwords is likely to not want to be logged for security reasons.

Modifying and forking reporters for each and every single case isn't practical (once for file logging, for console, for udp, etc)

How this is to be done can be discussed. Perhaps a callback filter function, or a plugin for good itself.

See https://www.npmjs.com/package/blur  for reference

**Comment by AdriVanHoudt** [comment]
I like the filter idea, although would it also be possible to filter out certain routes from the `response` even for example? There are some I don't want logged in console for example

**Comment by arb** [comment]
What would the API for this look like? The problem with the expectation that you can configure everything with just JSON, so specifying a function in-line wouldn't really work.

**Comment by danielb2** [comment]
``` javascript
var options = {
    filter: {
    	creditcard: 'creditcard',
    	cvv: 'censor',
    	unusedfield: 'remove'
    },
    opsInterval: 1000,
    reporters: [{
        reporter: require('good-console'),
        events: { log: '*', response: '*' }
    }, {
        reporter: require('good-file'),
        events: { ops: '*' },
        config: './test/fixtures/awesome_log'
    }, {
        reporter: 'good-http',
        events: { error: '*' },
        config: {
            endpoint: 'http://prod.logs:3000',
            wreck: {
                headers: { 'x-api-key' : 12345 }
            }
        }
    }]
};
```

Where the keys are fields that will be modified, and the values are modification types. The different types of modification are:

* `creditcard` - This filteres all but the last four characters. For example: 1234567890 -> XXXXXX7890
* `censor` - Replaces contents with `[FILTERED]`
* `remove` - Removes from logging completely.

**Comment by arb** [comment]
I like `remove` and `censor`. I don't like `creditcard` as it has an extremely specific use case and if we add one super custom one like that, then we'll end up adding a bunch more.

**Comment by danielb2** [comment]
creditcard can be used for anything where it's useful to validate that the information is correct without compromising the security of what's logged. It's not restricted to creditcard. Perhaps `partial` can be used to describe it if that makes it feel less specific.

**Comment by arb** [comment]
Lets make this the API:

`censor` - replace entire value with "*"
`remove` - completed removes the value from the object before sending the data out to the reporters
`partial` - expressed via "partial:n" where `n` is the last `n` characters to remain intact.

**Comment by danielb2** [comment]
Let's make it `n:partial`  also so it can be reversed ?

**Comment by danielb2** [comment]
Also,  I think the `*` for censor may not be obvious enough. I like `[FILTERED]` better because it will be obvious for anyone reading it.  `*` can be a valid character as well whereas `[FILTERED]` isn't likely to be

**Comment by gergoerdosi** [comment]
How about using a regex instead of `n:partial` or `partial:n`? So:

```javascript
creditcard: /(\d{4})$/
```

We could then have a basic function that replaces the matched string with `X` characters, something like:

```javascript
string = string.replace(regex, function ($0, $1) {
    
    return (new Array($1.length + 1).join('X'));
});
```

Using a regex would allow more complex cases too:

* `/(\d{4})$/`: `12345678` -> `1234XXXX`
* `/^(\d{4})/`: `12345678` -> `XXXX1234`
* `/(PRIVATE\d{3})/`: `PUBLIC-PRIVATE123-PUBLIC` -> `PUBLIC-XXXXXXXXXX-PUBLIC`

**Comment by lloydbenson** [comment]
seems like if rather than just doing regex, you may want to it to be any function that takes in a string and outputs a string.  Than you can use blur, a regex, or whatever else in order to get it to look how you want.  If you want FILTERED or * it shouldnt matter.

**Comment by arb** [comment]
I think the regex is the winner. The problem with functions is you can't JSON.stringify them while you can do it with REGEX.

**Comment by lloydbenson** [comment]
good point.  regex it is.
