### ISSUE TITLE
Interested in a logstash reporter?

### ISSUE THREAD

**Issue by phal0r** [hapijs/good#318]
Hey guys,

we have created a small good reporter for communicating with a logstash instance via the lumberjack protocol. If you like it we can make a pull request to add it to the community contributions section.

This is the repo: https://github.com/atroo/hapi-good-logstash

Thanks in advance!

**Comment by lloydbenson** [comment]
That'd be great!  Thanks!

**Comment by atroo** [comment]
here it is: https://github.com/hapijs/good/pull/319

thank you for the great work all around the whole hapi project We love it!

**Comment by lloydbenson** [comment]
Closed via https://github.com/hapijs/good/pull/319 and you're welcome!
