### ISSUE TITLE
Doesn't log any request

### ISSUE THREAD

**Issue by JbIPS** [hapijs/good#326]
Hi,

I'm using good 6.0.0 with good-file 5.0.0 to log any incoming request. Here's my conf:
```js
good: {
      reporters: [{
        reporter: require('good-file'),
        events: {'request': '*'},
        config: 'log/requests.log',
      }],
      requestPayload: true,
    }
```
I see some logs on my console when some routes are called, but nothing shows up in my log file. I tried different events (log, ops, response) and they're logged perfectly, but nothing for request.

I looked into the code and saw on [this commit](https://github.com/hapijs/good/commit/d52fec5f3b8c5d12d6604b1a405bb181d1da8375#diff-9a3ce09856114605620e98d815bd93e1L14) that incoming request event is now `request-internal` but the listener [here](https://github.com/hapijs/good/blob/master/lib/monitor.js#L162) is still on `request`. I tried changing this line to 
```js
self._state.handlers['request-internal'] = self._requestLogHandler.bind(self);
```
and it's logging my request perfectly.

So, am I doing something wrong or does it need to be changed?

Thank you

**Comment by arb** [comment]
The `request` event will only fire when you do `request.log` in a handler. You'd be better served with `response` events or using the extension method for "request-internal". 

Be sure to heed the warnings about listening to internal events. IE, they will happen more often than you think, and can change at any time without warning.
