### ISSUE TITLE
Be able to truncate/drop big response payloads for logging

### ISSUE THREAD

**Issue by SzaboAdamImre** [hapijs/good#331]
Hello!

I'm using the following configuration for logging:
```javascript
logging: {
        reporters: [{
            reporter: 'good-console',
            args: [{log: '*', response: '*', error: '*', request: '*'}]
        }, {
            reporter: 'good-file',
            args: ['/data/logs/server.log', {log: '*'}]
        }, {
            reporter: 'good-file',
            args: ['/data/logs/request.log', {response: '*', error: '*', request: '*'}]
        }, {
            reporter: 'good-file',
            args: ['/data/logs/error.log', {error: '*'}]
        }],
        opsInterval: 1000,
        logRequestPayload: true,
        logResponsePayload: true
    }
}
```
Note that request/response payload logging is enabled.

In one of my API methods, the returned data got pretty big (it was around 7 MBs).
Besides that this result is too big (and it got changed), the symptom of this was the following:
- One CPU core went from ~1% to 100%
- The server could not respond to anything

With some debugging we realized that the system got stuck in the good-console file's JSON serialization (maybe with an infinite loop - didn't really check, we let it go for a minute or so, and it didn't check anything).

So, I'm thinking about if there is a way, to filter big result sets from serialization? (for example the XLS download's byte code gets also written to the logs, which is completely unnecessary).

Both the truncation (f.e. only the first 100 chars get written), and complete drop (response: [too big]) would be a good solution, in my opinion - but I don't whether these are currently supported, or can be implemented at all?

Thx

**Comment by arb** [comment]
Logging that kind of information out to the console is a bad idea for that very reason. If you want logging that verbose you should just use the file logging. The console was primarily meant for ops and errors.

There is also some work being done in good-console to toggle the payload logging independent of the global good options. https://github.com/hapijs/good-console/issues/36
