### ISSUE TITLE
Change Log Headers Options

### ISSUE THREAD

**Issue by arb** [hapijs/good#336]
With more headers and payloads being added via the "wreck" event, the `includeRequestPayload` type options are becoming a little cumbersome to work with. We need a more maintainable way to control what is sent out from good.

**Comment by AdriVanHoudt** [comment]
A master option and an option per event type?

**Comment by arb** [comment]
I want less options and I think that route will just add more.

**Comment by AdriVanHoudt** [comment]
Less options will be better idd. How about a 'payload' option where you define the events it's appliable on? like `includeHeaders: ['wreck', 'response']` or `includeHeaders: 'response'` ?

**Comment by arb** [comment]
While you're in there, curry the `GreatResponse` constructor.
