### ISSUE TITLE
Update Reporter Interface example in README

### ISSUE THREAD

**Issue by KITSJosephChapman** [hapijs/good#343]
An example of how to use `init` method would be helpful in the docs

**Comment by arb** [comment]
`init` is called directly by good and not the developer... what example are you looking to see?

**Comment by KITSJosephChapman** [comment]
Apologies I though this:
```
An init method with the following signature function init (readstream, emitter, callback) where:
readstream - the incoming readable stream from good. This stream is always in objectMode.
emitter - the good event emitter. The emitter will emit the following events:
stop - always emitted when the hapi server is shutting down. Perform any tear-down logic in this event handler
```
meant that it was is overridable

**Comment by arb** [comment]
It's more of a documentation of how to create your own good-reporter if you wanted to. If the documentation in that area isn't clear, documentation PRs are always welcome.

**Comment by osukaa** [comment]
@arb do you mean an example or just a better written doc to describe that this is the interface to implement for a good reporter?

**Comment by arb** [comment]
A better written doc about rolling your own reporter. The existing set of reporters offers plenty of examples in my opinion.

**Comment by osukaa** [comment]
@arb could you checkout if what I did was the correct thing?
