### ISSUE TITLE
Clean Up

### ISSUE THREAD

**Issue by arb** [hapijs/good#344]
Do this: https://github.com/hapijs/contrib/issues/31

**Comment by pon** [comment]
I believe this is the current status of this repo:

- [x] Remove Makefile and switch to using npm scripts (see hapi package.json)
- [ ] Remove root index.js (point package.json to lib/index.js)
- [ ] Replace package.json licenses array with single license key and "BSD-3-Clause" value
- [ ] Update code style to stop putting functions on single line (new lab will error on that lint warning)
