### ISSUE TITLE
Log requests does not work

### ISSUE THREAD

**Issue by thorque** [hapijs/good#358]
Hi,

I've trying to setup GOOD with GOOD-CONSOLE to log every request with this configuration:

```javascript
server.register({
   register: Good,
    options:{
        reporters: [{
            reporter: require("good-console"),
            events: {
                response: "*",
                log: "*",
                "request": "*"
            },
            config: {
                format: "DDMMYY/HHmmss.SSS",
                utc: false
            }
        }]
    }
}, function(err){
    if (err){
        throw err;
    }
});
```

But only the responses are logged.
What do I wrong?

Thanks 
Thorsten

**Comment by arb** [comment]
Please review the documentation for good. `request` events are those emitted when `request.log()` is called. If you need reporting on incoming responses, try using an `extension` option and listen for 'request-internal'. Make sure you read the documentation on that event as it is fired multiple times per request.

**Comment by thorque** [comment]
ah...understanding. I assumed that i don't need to call request.log() to log. 

What is the best approach to log every request in a kind of debug mode?

**Comment by arb** [comment]
> try using an `extension` option and listen for 'request-internal'

and use an environment flag.

**Comment by davidbenko9** [comment]
Is there a way to log the payload using 'request-internal'?

**Comment by davidbenko9** [comment]
Also, is there a way using exensions to only log [request-internal,received] instead of every event associated with 'request-internal'?
