### ISSUE TITLE
Excluding log messages based on tags

### ISSUE THREAD

**Issue by Bondza** [hapijs/good#364]
Hey!

I've been using good reporters for a while now, and so far I think it's awesome :)

Is it possible to exclude log messages by tags? For example, for response events when there is an error this is automatically logged with the ```tags=["handler","error"]``` and a response with ```20X``` has ```tags=["handler"]```. I wonder if it is possible to apply filters such that I can log the errors and ```20X``` responses to separate files? I am guessing that setting filter to ```{ response: "handler" }``` would include errors since handler is present in both cases?

I think the ```censor``` and ```remove``` options do not provide the functionality that I want. As far as I can tell they affect a whole event type such as ```log``` or ```response```, is this how they work?

**Comment by arb** [comment]
No, there is currently not a mechanism to filter based on exclusions. You can create your own reporters or try changing https://github.com/hapijs/good-squeeze as that is the module that ultimately is responsible for tag-based filtering.

Filtering by tags is an OR operation, so any response events that have the "handler" tag would be logged.

`censor` and `remove` only affect request and response payloads. It is useful for removing credit card or other personal information that shouldn't be logged.

**Comment by Bondza** [comment]
Alright, thanks for the info :)
If I get around to implement this, should i open an issue there instead?

**Comment by arb** [comment]
Yep.
