### ISSUE TITLE
Can you ensure a header is always logged, when present?

### ISSUE THREAD

**Issue by walling** [hapijs/good#366]
A service receives some information via a header (fx. `X-Request-ID`) to track/debug requests through multiple systems. Is it possible to configure **good** to include this in the log output, when present?

**Comment by arb** [comment]
Try setting the `requestHeaders ` option to `true`. Also, make sure that any reporters you are using actually log the header values. I know good-file DOES. good-console does not.

**Comment by walling** [comment]
It works, thanks.
