### ISSUE TITLE
Logging blocks process for large request payloads

### ISSUE THREAD

**Issue by timoweiss** [hapijs/good#370]
Hi, we are currently experiencing an issue with the logging of request payloads.
We're using hapi@8.4.0 and good@6.1.4

We have implemented a simple image-upload, which streams the data into a couchdb.
If we upload a file with about 4 Mb, that server gets block for about 10sec after the upload has been finished.

After profiling we found out that the logging is the bottleneck. Our good-setup looks like the following:

```javascript
var options = {
    reporters: [{
        reporter: require('good-file'),
        events: {error: '*', request: '500'},
        config: '/var/log/locator/internalError.log'
    }, {
        reporter: require('good-file'),
        events: {request: '400'},
        config: '/var/log/locator/clientError.log'
    }, {
        reporter: require('good-console'),
        events: {error: '*', request: '500'}
    }, {
        reporter: require('good-file'),
        events: {response: '*', log: '*', request: '*'},
        config: '/var/log/locator/locator.log'
    }, {
        reporter: require('good-file'),
        events: {log: 'corrupt'},
        config: '/var/log/locator/corruptFiles.log'
    }],
    requestHeaders: true,
    requestPayload: true,
    responsePayload: true,
    filter: {
        file: 'remove',
        password: 'remove'
    }
};
```
We thought that adding the filter for `file` will solve the problem.
Is there anything we are doing wrong?

Thanks in advance!

**Comment by arb** [comment]
Well it looks like you're logging "request" events three times to three different files so that probably isn't helping. I notice you are doing `request`: '500', etc. If your intent is to filter based on status code, that isn't going to work as you can only filter by tags.

You could try not logging request payloads as well see how that impacts things.

**Comment by timoweiss** [comment]
Yes, we have one for internal errors, client errors and one for all. Maybe we will refactor that.
We've created tags named '500' etc. So this shouldn't be the problem.

If we set the option `requestPayload` to `false`, the server stops blocking after uploading a file.

**Comment by timoweiss** [comment]
Logging the payload "manually" seems not to block:
```javascript
// log the payload on error
server.on('response', (request) => {

    if (request.response) {
        var code = request.response.statusCode;
    } else {
        return;
    }

    if (code === 400 && code < 500) {
        // don't log files
        if (request.payload && !request.payload.file) {
            request.log(['ark', 'error', 'payload', '400'], request.payload);
        }
    } else if (code >= 500) {
        request.log(['ark', 'error', 'payload', '500'], request.payload)
    }
});
```

**Comment by timoweiss** [comment]
After experiencing this hiccup I saw this right now:
```
Debug: internal, implementation, error 
    RangeError: Invalid string length
    at join (native)
    at Object.stringify (native)
    at stringify (/home/locator/ark/node_modules/good-file/node_modules/json-stringify-safe/stringify.js:5:15)
    at internals.SafeJson._transform (/home/locator/ark/node_modules/good-file/node_modules/good-squeeze/lib/safe-json.js:33:15)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:291:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Writable.write (_stream_writable.js:206:11)
    at ondata (_stream_readable.js:520:20)
```
I missed that one before.

**Comment by arb** [comment]
@timoweiss are you still having issues? Otherwise I'd like to close this.

**Comment by timoweiss** [comment]
We removed good after that. I'm not sure what it was but I think it has something to do with replying a boom object. We can close it for now. I'll try to reproduce it and reopen this issue if necessary. Thanks!
