### ISSUE TITLE
hapi  register error is undefined both on sucess and error

### ISSUE THREAD

**Issue by whisher** [hapijs/good#373]
Sorry to bother you.
I'm wondering if there is something wrong with this code or outdate doc or may be a bug:

```javascript
var options = {
    opsInterval: 1000,
        reporters: [
            {
                    reporter: require('good-console'),
                    events: { log: '*', response: '*' }
            },
            {
                    reporter: require('good-file'),
                    events: { ops: '*' },
                    config: './log/good.log'
            }
        ]
};
server.register(
    {
            register: require('good'),
            options: options
    },
    function (err) {console.log(err)
        if (err) {
                    return console.error(err);
            }
            server.start(function () {
            console.info('Server started at ' + server.info.uri);
                });

    }
);

```
even if I set 
```javascript
config: './thereIsNotDirHere/good.log'
```

and I can see the error console.log(err)
get undenifed value

**Comment by arb** [comment]
What is the issue? Are you not seeing ops information in ./log/good.log?

**Comment by whisher** [comment]
even if there is an error
config: './thereIsNotDirHere/good.log'
the err is undefined

**Comment by arb** [comment]
That should be working. Try removing all your node_modules and reinstalling them. See if that changes anything. Also, which version of good are you using?

**Comment by whisher** [comment]
"good": "^6.3.0",
"good-console": "^5.0.2",
"good-file": "^5.0.1",

**Comment by arb** [comment]
Are you seeing logging information to the console?

**Comment by whisher** [comment]
If I put 

function (err) {console.log(err)

I can see undefined

**Comment by arb** [comment]
I need clarification - is the issue that you are not seeing "ops" events being logged to './log/good.log' or is the issue that if you pass in a non-existant file, as the configuration option to good-file, and the error isn't being sent back to you in the callback?

**Comment by whisher** [comment]
The issue is:

> the issue that if you pass in a non-existant file, as the configuration option to good-file, and the error >isn't being sent back to you in the callback?

the error in the callback is undefined

so pass in a non-existant file is it an error or not ?
if not what's an error in the callback ?

I need clarification :)

**Comment by arb** [comment]
This is more an issue in good-file and not good itself. Please see this related issue - https://github.com/hapijs/good-file/issues/55
