### ISSUE TITLE
avoid certain network monitoring operations

### ISSUE THREAD

**Issue by boneskull** [hapijs/good#376]
Is it somehow possible to avoid, for example, the `concurrents` operation from being called?

I have a unique use case in that my listener does not have a `getConnections()` method.

**Comment by boneskull** [comment]
(or any notion of a "connection", for that matter)

**Comment by arb** [comment]
Short answer, "no". 

Long answer - we could add some protection code around that specific code to just execute a noop in the instances where `getConnections()` doesn't exist. That seems like a very specific edge case though. I think a better solution would be for you to monkey patch a `getConnections` method to whatever listener you are using.

**Comment by boneskull** [comment]
Yeah.  I'm thinking I may be able to wrap my listener in a proper `net.Server` as well.  Thanks.
