### ISSUE TITLE
Monitor shouldn't be started until server is started

### ISSUE THREAD

**Issue by btmorex** [hapijs/good#377]
Currently, the monitor is started as soon as the plugin is registered. Because of that, node will not cleanly exit unless server.stop() is called even if server.start() was never called, which doesn't really make sense.

**Comment by arb** [comment]
Are you suggesting waiting for the start of the server to start the monitor?

**Comment by btmorex** [comment]
Yes, I'm suggesting starting it when the server start event fires. Ideally it would only start if there was a reporter configured for ops too.

**Comment by kevinmstephens** [comment]
This would prevent users from using `server.log` in plugin registration and whatever module initialization might be done during registration. This seems highly undesirable. This request should be made specific to the "ops" event.

**Comment by arb** [comment]
So what are we doing here? Only start the "ops" event when the server actually starts? Is that the request?
