### ISSUE TITLE
Logging custom requestId

### ISSUE THREAD

**Issue by netei** [hapijs/good#388]
See https://github.com/hapijs/hapi/issues/2792

It would be great if they was a way to access to the requestId of the request so that you can use logs by searching for a requestId.

I also think it would make sense to expose the whole request data. 

Would you accept a pull request for that ?

Should I just change the "Great" event ins `lib/utils` ?

Which events could I change ? All of them ?

**Comment by arb** [comment]
The request ID is available in `GreatError`, `GreatResponse`, and `GreatRequest ` as the `id` field. I'm hesitant to include the *entire* request object as it it rather large and most of it wouldn't be useful for logging purposes.

Is there something missing that you need?

**Comment by netei** [comment]
The request.id is different from request.app.requestId (I'm willing to access the second one).

**Comment by netei** [comment]
How can we pass the request.id when doing a `request.log()` ?

**Comment by arb** [comment]
You could try passing it in as `data` - https://github.com/hapijs/hapi/blob/master/API.md#requestlogtags-data-timestamp

**Comment by netei** [comment]
I wanted to pass the data without having to specify it each time. I think I'm going to do a wrapper function that calls request.log itself
