### ISSUE TITLE
Not outputting to Console

### ISSUE THREAD

**Issue by aaronhumerickhouse** [hapijs/good#389]
I'm not getting any output from good when interacting with my application.  I believe it's an environment issue because others are capable of getting the logs, but I have no clue what to look for. 

System: `good-console@4.1.0`, `good@5.12`, `node -v -> v0.10.35`.    

Config:

```javascript
www: {
  
  server: {
    connections: { state: { strictHeader: false } }
  },
  
  connection: {
    port: process.env.PORT || 3091,
    router: { stripTrailingSlash: true }
  },
  
  plugins: {
  
    good: { // logging
      register: require('good'),
      options: {
        reporters: [{
          reporter: require('good-console'),
          events: [{ log: '*', request: '*', response: '*', proxy: '*', auth:'*' }]
        }]
      }
    }
  }
}
```

server.js
```javascript  
var wwwConfig = _.cloneDeep(config.get('www'))
var plugins = _.values(wwwConfig.plugins)
var pluginNames = _.keys(wwwConfig.plugins)
  
console.log('Registering Plugins:', pluginNames.join(', '))
console.log('Plugins:', JSON.stringify(plugins))
server.register(plugins, function(err) {
    if (err) throw err
  
    // register routes
    server.route(require('./app/routes'))

    server.start(function() {
    console.log('Server running at:', server.info.uri)
  })
})
```
Output:

    => Registering Plugins: good 
    =>Plugins: [{"register":{},"options":{"reporters":[{"events":[{"log":"*","request":"*","response":"*","proxy":"*","auth":"*"}]}]}}]
    =>Server running at: http://Aaron-Hs-MacBook-Pro.local:3091

**Comment by lloydbenson** [comment]
Have you tried just updating to the latest versions of good and good-console?  Or do you have to specifically use those versions?

**Comment by aaronhumerickhouse** [comment]
It's an existing project that I don't maintain, so I don't want to have to update it.  But, I tried that locally and had no luck.  I'm still not getting any output with `good-console@5.1.0` and `good@6.4.0`

**Comment by arb** [comment]
How do you know it's not working? Have you made any requests against this server?

**Comment by aaronhumerickhouse** [comment]
Yes, I'm launching it locally, then interacting with the site.  I've performed the same actions as somebody else who is getting output.

**Comment by lloydbenson** [comment]
https://github.com/hapijs/good.  If you look at the documentation, the good-console should be:

```
var options = {
    opsInterval: 1000,
    reporters: [{
        reporter: require('good-console'),
        events: { log: '*', response: '*' }
    }, {
        reporter: require('good-file'),
        events: { ops: '*' },
        config: './test/fixtures/awesome_log'
    }, {
        reporter: 'good-http',
        events: { error: '*' },
        config: {
            endpoint: 'http://prod.logs:3000',
            wreck: {
                headers: { 'x-api-key' : 12345 }
            }
        }
    }]
};
```
Note how events doesn't have an array but instead of list of objects.

**Comment by aaronhumerickhouse** [comment]
Updated with no luck.

```javascript
    good: { // logging
        register: require('good'),
        options: {
          reporters: [{
            reporter: require('good-console'),
            events: { log: '*', request: '*', response: '*', proxy: '*', auth:'*' }
          }]
        }
      }
```

**Comment by lloydbenson** [comment]
I'd say boil this down into a more simple example.  My guess here is your plugins var isn't exactly what you expect.  Do you know what that looks like?  Based on your output above:

=>Plugins: [{"register":{},"options":{"reporters":[{"events":[{"log":"*","request":"*","response":"*","proxy":"*","auth":"*"}]}]}}]

It seems like its not registering good.  Can you try instead of using your "plugins" var, just try putting in directly there?  I think when you use the plugins var you have good in that as well, and I don't think thats the right format as you want the stuff after good.

**Comment by arb** [comment]
Is this still an issue?

**Comment by aaronhumerickhouse** [comment]
My apologies for not getting back.  I restarted my computer (twice) and it finally started working.
