### ISSUE TITLE
Pull ops event out

### ISSUE THREAD

**Issue by arb** [hapijs/good#392]
I'd like to remove the "ops" event logic and emitting from the internals of Good. I'd like to make use of the Ops event in a new module, but I don't need the baggage of the rest of Good.

**Comment by fhemberger** [comment]
Is this feature even widely used? I think many projects are already using unified monitoring tools throughout their whole stack that cover the same metrics that the "ops" event provides.

As logs and metrics are a slightly different concern anyways, it might make sense to split them into a different module.

**Comment by AdriVanHoudt** [comment]
I only use it to monitor stuff in dev

**Comment by savardc** [comment]
Agree, it's nice to have for dev but I don't think it needs to be part of Good

**Comment by arb** [comment]
Check out Oppsy https://github.com/hapijs/oppsy/pull/1
