### ISSUE TITLE
Remove Wreck Logging

### ISSUE THREAD

**Issue by arb** [hapijs/good#402]
It doesn't work right and there are way too many questions and bugs surrounding it at present. Once the issue is resolved, I'll be more than happy to add it back in.

https://github.com/hapijs/wreck/issues/111

**Comment by ldesplat** [comment]
I think it may be interesting to add listeners to outgoing http calls instead of just doing Wreck logging.. I've seen that somewhere and may actually cover all cases. The problem is we may be logging way too much, but it's a start?

**Comment by arb** [comment]
Yeah that would be a better solution in the short term for sure.
