### ISSUE TITLE
log to chrome?

### ISSUE THREAD

**Issue by daslicht** [hapijs/good#409]
Hi,
is it possible to log to the browser console like chomelogger?

**Comment by daslicht** [comment]
noone ?

**Comment by AdriVanHoudt** [comment]
I know if you do console.log and have node inspector open is will also log to the console of node inspector (which is chrome dev tools)

**Comment by arb** [comment]
This module is for logging to a variety of node transports. If you can create a good reporter that listens on a socket then I assume it's possible to log to a running Chrome instance. That is well outside the intent of this module so you're kind of on your own if you still want to do this.
