### ISSUE TITLE
Unable to get request payload to console

### ISSUE THREAD

**Issue by cyberwombat** [hapijs/good#422]
According to what I am reading this should print the request payload to the console:

    {
    register: require("good"),
    options: {
      requestPayload: true,
      responsePayload: true,
      requestHeaders: true,
      reporters: [{
        reporter: require('good-console'),
        events: {
          log: '*',
          response: '*',
          request: '*'
        }
      }]
    }

But it does not. I only ever see the response whether it passed or failed Joi validation. The data is sent as json and is making its way to the database so it's certainly there. 

Is this not correct? Thanks. 

     "good": "^6.4.0",
     "good-console": "^5.2.0",

**Comment by arb** [comment]
https://github.com/hapijs/good-console/issues/36

Logging payloads to the console doesn't make sense. Log to a file instead.

**Comment by cyberwombat** [comment]
Why doesn't it make sense? I am debugging and watching my console trying to understand why my request fails validation. Right now I have to disable validation and console log it from my controller which is annoying. Filling up a log file and tail it just doesn't seem to be more efficient. But ok.

**Comment by arb** [comment]
Are you doing this to try to debug an issue or doing this to consistently log information as long as the server is running? Those are two different things.

**Comment by cyberwombat** [comment]
Well debug. And sometimes this is remote like on Heroku where file logs are a girnormous pain when I can just read the console easily using Heroku's tools.

**Comment by arb** [comment]
You may want to check out the `debug` option when creating a new server... https://github.com/hapijs/hapi/blob/master/API.md#new-serveroptions and scroll down to `debug`.

**Comment by cyberwombat** [comment]
Thanks! that will do the trick.

    const server = new Hapi.Server({
     debug: {
       request: ['received']
    }});
