### ISSUE TITLE
Not possible to update Hapi > 8 cause good. 

### ISSUE THREAD

**Issue by StarpTech** [hapijs/good#426]
Hi I can not update hapi because good needs "hapi": ">=8.x.x". Is any update planned?

**Comment by AdriVanHoudt** [comment]
what version are you upgrading from/to?

**Comment by StarpTech** [comment]
From 11.1.4 to 12.0.1 then I get an installation error that good requires hapi >= 8.0.0

**Comment by AdriVanHoudt** [comment]
weird that should work (try http://semver.npmjs.com/)

**Comment by StarpTech** [comment]
Yes you're right I will check it again. I will report.
