### ISSUE TITLE
API example doesn't work

### ISSUE THREAD

**Issue by hulbert** [hapijs/good#427]
https://github.com/hapijs/good/blob/master/API.md#reporter-interface

AFAICT the readable stream is in object mode which cannot be piped to `process.stdout`, so a TypeError is thrown `TypeError: invalid data`.

**Comment by arb** [comment]
Yeah you're right, it should be sent through `GoodSqueeze.SafeJson` before `process.stdout`. I'll take a doc PR to correct this.
