### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by miksago** [hapijs/good#434]
Hi, I've noticed that new versions of this module come out, and it'd be great to know what has changed as to assess priority of updating; However, this currently seems hard to no unless you go commit by commit reviewing changes as you don't seems to have any changelog — none as a text file in the repository, and releases / tags have no descriptions.

It'd be really great to be able to find out what changed between releases.

**Comment by Marsup** [comment]
We have a strict usage of issues in the organization. You can go through the github milestones and see what was done.

**Comment by arb** [comment]
Check out https://github.com/hapijs/good/milestones?state=closed to see all the past milestones. It's a pain to keep a changelog up-to-date as well as make sure things have proper milestones. As this module doesn't change all that often (usually) I don't think a change log would be that useful. 

There is also this query https://github.com/hapijs/good/issues?q=is%3Aissue+label%3A%22release+notes%22+is%3Aclosed which gives you all the release notes for every major version bump. Between those two things, you should be able to find what you need.

**Comment by Marsup** [comment]
Also there's a tool used in hapijs.com that is waiting for generalization to all hapi modules to create the same kind of changelog, until someone volunteers...
