### ISSUE TITLE
New Lead Maintainers

### ISSUE THREAD

**Issue by arb** [hapijs/good#457]
I'm looking for new community members who are interested in taking over some of the side modules related to good.

Up for grabs

- https://github.com/hapijs/good-console
- https://github.com/hapijs/good-http

**Comment by thebergamo** [comment]
I will check `good-console` @arb  :)

**Comment by vdeturckheim** [comment]
Showing interest to `good-http` :wink:

**Comment by genediazjr** [comment]
I'm interested to both

**Comment by arb** [comment]
@thebergamo, @vdeturckheim and @genediazjr to get started, read and familiarize yourselves with everything in https://github.com/hapijs/contrib That pretty much lays out what it means to be part of the hapijs org as a lead maintainer.

**Comment by vdeturckheim** [comment]
LGTM

**Comment by thebergamo** [comment]
LGTM

**Comment by arb** [comment]
good-udp has be taken over by @vdeturckheim. Still working out good-http and good-console.

**Comment by genediazjr** [comment]
congrats @vdeturckheim 🎉

**Comment by vdeturckheim** [comment]
Thanks 😄

**Comment by thebergamo** [comment]
@arb can I help with anything in good-console?
