### ISSUE TITLE
Invalid monitorOptions options child "reporters" fails because ["reporters" must be an array]

### ISSUE THREAD

**Issue by ms88privat** [hapijs/good#461]
I can not run the example code because of the following error:

Invalid monitorOptions options child "reporters" fails because ["reporters" must be an array]

**Comment by nearengine** [comment]
This actually caught me up today while getting started with good :smile: Looks like the README on master is for an upcoming release, check out https://github.com/hapijs/good/tree/v6.6.0

**Comment by arb** [comment]
The badge on the README is the current version on npm. There should (hopefully) be a release candidate version of good7 by the end of the week.

**Comment by ms88privat** [comment]
@arb :+1: 

Does it come soon?
