### ISSUE TITLE
README woefully out of date

### ISSUE THREAD

**Issue by sevenbitbyte** [hapijs/good#465]
Your first point of contact, the README.md doesn't even show a working example. Is this project still alive?

Here's a working example for 6.6.0

```
Server.register({
  plugins: [{
    register: require('good'),
    options: {
      reporters: [{
        reporter: require('good-console'),
        events: {
           response: '*',
           log: '*'
         }
      }]
    }
  }]
})
```

**Comment by gergoerdosi** [comment]
You can find the documentation for 6.6.0 here: https://github.com/hapijs/good/tree/v6.6.0

**Comment by MrBri** [comment]
I spent to much time trying to get this to work using the latest version from npm and going off the master README. I kept thinking my setup was wrong. Lucky found this issue when I was about to give up and use something else.
Think the master README of github should match what's on npm. Or least a message saying it's a previous version or something.

**Comment by Marsup** [comment]
It's like that on almost every node module out there, you'd better get used to it.

**Comment by gergoerdosi** [comment]
GitHub is for working on the code. Releases are on npm. If you use the latest version from npm, why don't you read the latest README on npm? https://www.npmjs.com/package/good

**Comment by mtharrison** [comment]
A slight issue with that is that the README on npm links through to the master API reference.

**Comment by arb** [comment]
Sorry if this is confusing; I'm trying to finish a major version update. @Marsup is correct though, many npm modules keep GitHub up-to-date code wise and use npm for releases. The npm page for this package is up-to-date with a working example.
