### ISSUE TITLE
Good 7.0.0 Release Candidate

### ISSUE THREAD

**Issue by arb** [hapijs/good#468]
To get started, you'll need to install the good release candidate with `npm install good@7.0.0-rc1`. That will give you the release candidate for good version 7. To date, only three reporters have been updated to the new interface - good-console, good-http, and good-file. 

When installing the reporters, first start with `npm view [module_name] versions`. This will list all the published versions for the reporter. Find the latest version and *explicitly* install that version. None of the reporters have their "latest" tags updated (yet). For example, to install the latest version of good-console, you would need to do `npm install good-console@6.0.0`. Just `npm install good-console` will give you the 5.x.x version which is not compatible with the good release candidate. 

Do not use this issue for reporting any issues, this is just for coordinating the release candidate. Log issues the normal GitHub way and mention the version you are using. Release notes can be found at #467

**Comment by fhemberger** [comment]
With the new classes for the reporters, it should be easy to let reporters like `good-loggly` and `good-influxdb` inherit from `good-www`, as only the output needs to be formatted differently.

**Comment by spalger** [comment]
Can you tag the good rc as such and re-tag the latest 6.x release as latest?

Ideally this would work until 7.0 is released:
```sh
npm install good good-console good-squeeze
```

![image](https://cloud.githubusercontent.com/assets/1329312/14487148/ceadf2d8-0115-11e6-87a5-821e74eac703.png)

**Comment by arb** [comment]
Thanks @spalger. I sort of assumed npm wouldn't automatically tag an "RC" as latest; guess I was wrong.
