### ISSUE TITLE
Add line break after a log message

### ISSUE THREAD

**Issue by idosh** [hapijs/good#470]
Currently when a new log message is written to destination (be it stdout, stderr or a file), it doesn't break the line. All logs are being written to the same line.

Version: 7.0.0-rc1

**Comment by arb** [comment]
One of your streams is going to have to put a new-line in somewhere. I know https://github.com/hapijs/good-squeeze#safejsonoptions-stringify has a `separator` option for this purpose.

**Comment by idosh** [comment]
What if I want to use good-console, I'm unable to do so if SafeJson attached to the stream?
is there any option in good itself to add a line break?

`[TypeError: Cannot assign to read only property 'data' of {"event":"log","timestamp":1460961529581,"tags":[],"data":"server running at http://shamun-ubuntu-laptop:3000","pid":19962}`

**Comment by arb** [comment]
Can you show me your stream pipeline that uses good-console? I can only assume you are writing to `process.stdout`. If that's the case, you'll need a transform stream, either your own or a prebuilt one, that appends "\n" to `data` in the `_transform` method of your stream.

**Comment by idosh** [comment]
That's exactly what I did. I created a new class which appends `\r\n`.
Thinking about publishing it for other developers
