### ISSUE TITLE
Ignore specific route

### ISSUE THREAD

**Issue by mugli** [hapijs/good#471]
I want to ignore specific routes (mainly for health check) from good access/request log, but cannot figure out which specific configuration to use on that route. Can anyone please help?

**Comment by arb** [comment]
What version of good are you using?

**Comment by mugli** [comment]
v6.6.0

**Comment by arb** [comment]
In the version 6 line of Good, the only way to really skip certain routes is to write your own reporter. In version 7, you can write a basic transform stream and look at the incoming request and determine whether or not to forward it on to the next stream in the pipeline.

**Comment by mugli** [comment]
Cool. Thanks. :)
