### ISSUE TITLE
Document `good` Route and Reply Config

### ISSUE THREAD

**Issue by arb** [hapijs/good#472]
Good will not attach `route.plugin.good` and `request.plugin.good` objects to all of the events that have `request` available. Include this in the docs and mention how you can use this for additional filtering logic.

See [this test](https://github.com/hapijs/good/blob/master/test/monitor.js#L767-L819) for an example.

**Comment by AdriVanHoudt** [comment]
wait so the point is you have manually set `request.plugin.good` ? I have not played around with good 7 so not sure what is going on :P

**Comment by arb** [comment]
You don't have to do anything. This is just *a* way you can pass route or request level config options into good if you want to. I imagine people using this for additional filtering rules.
