### ISSUE TITLE
Poor first developer experience

### ISSUE THREAD

**Issue by capelio** [hapijs/good#473]
I ran `npm install --save good`

I started digesting the README.

Two hours later I realized things weren't working because npm gave me `6.6.0` while the README is giving me `7.0.0-rc1`. I manually changed the branch so i could read the `6.6.0` README and problem solved.

However, this seems like a avoidable headache.

**Comment by arb** [comment]
Sorry for the confusion. Please see these related issues #466 #465

**Comment by capelio** [comment]
Not a worry. I just re-read my initial comment and I realized that I sounded rather grumpy. I should clarify my opinion: Good is amazing and the work the team does is amazing and I'd hate to leave you with the impression that this awesome library we get to use for **free** is anything other than greatly appreciated. :)

**Comment by danielb2** [comment]
FYI https://github.com/npm/newww/issues/1926

**Comment by arb** [comment]
There was an issue with README on npm being out of sync with what was supposed to be there. I opened an issue and was told it is a known issue with npm. I went through and fixed good and all the old good reporter plugins to be correct now. The npm README should be correct for old versions of all the node modules. Again; sorry for the confusion.

**Comment by capelio** [comment]
Thanks for the great communication @arb and @danielb2, it is much appreciated
