### ISSUE TITLE
Q - Best practices for centralized logging and performance monitoring

### ISSUE THREAD

**Issue by leobudima** [hapijs/good#474]
Hi - given that hapi is emitting both traditional logs and performance monitoring information, and the new release of good, is there a recommended approach to centralized performance monitoring/logging, or can someone share their production experience?

We are currently running (with another framework) an ELK stack for logs, which I realize is possible through good-logstash, but what about ops events, for which currently doesn't seem to be a way to transmit through tcp / udp? Up till now, we were sending data (again, from another framework) to collectd which feeds it to InfluxDB - is there anything comparable for hapi/good? 

Thanks!

**Comment by arb** [comment]
You can transmit anything though any transport. Create a new reporter, filter out everything but logs and the use a tcp or udp write stream to an endpoint. Also, the ops reporting part of good is it's own [module](https://github.com/hapijs/oppsy), so you can use it directly if that would suite your needs better.

**Comment by leobudima** [comment]
Thanks! I'll dig in and create my own - I realize that a lot of effort has gone into cleaning and simplifying good in the last revision, with moving to streams - hopefully community will quickly react and broaden support for different protocols again. I'll do my best to contribute :) Thanks again!
