### ISSUE TITLE
Is there any list of all the good reporters?

### ISSUE THREAD

**Issue by idosh** [hapijs/good#476]
I wonder if there is a list of all the good reporters something similar to the hapijs plugins list.
I've just published two reporters maybe more people can find them useful.

**Comment by gergoerdosi** [comment]
I don't think there is a list, but you can do a search on npm: https://www.npmjs.com/search?q=good

**Comment by idosh** [comment]
I see, thanks :+1:

**Comment by arb** [comment]
There is a list [here](https://github.com/hapijs/good#existing-streams) but keep in mind, the goal of Good version 7 was to be able to use ANY off-the-shelf stream from npm. You can search with Google or npm and try to find a stream that suites your needs.
