### ISSUE TITLE
3rd party streams for good@7.0.0

### ISSUE THREAD

**Issue by fhemberger** [hapijs/good#479]
I wrote two streams compatible with good@7.0.0:

- [good-influx](https://github.com/fhemberger/good-influx) (replacing @totherik's implementation) and 
- [good-logstash](https://github.com/fhemberger/good-logstash)

In case you want to add 3rd party streams in the README again.

**Comment by leobudima** [comment]
Just wanted to say thanks, @fhemberger - exactly the two I need just these days!

**Comment by fhemberger** [comment]
@leobudima You're welcome, feedback is always appreciated!

**Comment by arb** [comment]
I'm actually trying to get away from "good-" streams. Part of the motivation for the good 7 rewrite was to allow users to use any off-the-shelf write or transform stream for their reporting needs without a proprietary interface.

That being said, please feel free to create additional streams that others can use with good! I would caution you though to make sure that you're not creating something that already exists and to be very careful when creating write streams. They are very hard to get write (I'm sure none of mine are 100% right FWIW).
