### ISSUE TITLE
How to customize data being passed to reporter?

### ISSUE THREAD

**Issue by NerdPad** [hapijs/good#481]
For every request my server receives, I would like to log few extra fields (user, a tracking id passed in the header).

I am using good-bunyan, and have an option to write a formatter for ```response``` event.

How can I customize the data that is passed to the reporter?

**Comment by arb** [comment]
What version of good? If it's 6, you'll need to write a customer reporter. If it's 7, you have a lot more options for how you can customize your event payloads.

**Comment by NerdPad** [comment]
I am using 6, and I was already using good-bunyan reporter, so I had to exclude ```response```, and handle it manually.

v7 just got released, so I will look into the transform, if that helps.

Thanks for the help.

**Comment by gilly3** [comment]
I have nearly the exact same question - I want to log the user name and a tracking id for each request.  I am also using v6.6 (of course, since v7 was only published yesterday).  Are there release notes?  What is the breaking change?

**Comment by arb** [comment]
https://github.com/hapijs/good/issues/467 are the release notes.

If you are using good 6 and you want to customize your outputs, you're only real option is to roll your own reporter. If you want to read up on doing that, start here https://github.com/hapijs/good/blob/v6.6.3/API.md
