### ISSUE TITLE
Do I have to use npm modules in order to use good reporters?

### ISSUE THREAD

**Issue by csaintc** [hapijs/good#497]
I'm confused by the documentation. From what I can tell, I pass the `node-module` name into the module field for a reporter.

Does this mean I have to expose any of the good reporters I write as NPM modules?

**Comment by arb** [comment]
Nope. From the documentation:

> `module` - a string that will be used to import a module from node_modules or a local file. Should export a single constructor function that can be invoked with new.

So `module` can be a npm module or a file path. Just a string that will have `require` called with that as the argument.

**Comment by csaintc** [comment]
Documentation seems fine. Another problem is: I have to provide an absolute path to my module and it's not super fun:
```
module: '/usr/src/app/lib/plugins/util/logging/bugsnagreporter',
```
