### ISSUE TITLE
help migrating v6 to v7

### ISSUE THREAD

**Issue by gr2m** [hapijs/good#500]
follow up for https://github.com/hapijs/good/issues/467#issuecomment-226545353

The update to v7 broke our usage at Hoodie, here’s a pull request with failing test on Travis: https://github.com/hoodiehq/hoodie/pull/478 – that’s expected and clear, it’s a breaking change after all.

I tried to look into it myself and figure out how to adapt our good usage in this file: https://github.com/hoodiehq/hoodie/blob/master/server/plugins/logger.js but had no luck.

I’d appreciate if you could give me some pointers on how to best migrate to v7, thanks a lot

**Comment by arb** [comment]
If you're committed to using `npmlog`, you'll have to write your own write stream, implement a `_write` method and then call into the `npmlog` like you're doing now. Check good-http for an example. Specifically the [`_write`](https://github.com/hapijs/good-http/blob/master/lib/index.js#L41-L55) method. In there you'd check the event type and call the different `npmlog` methods.

You can remove the GoodFilter out of there too if you want and include an instance of it before your new write stream to keep your writeStream more modular.

**Comment by gr2m** [comment]
Thanks for the pointers :) I’ll give it another try! 

Unfortunately we don’t have a Hoodie hoodie yet. I know, I know. But it keeps us going, it’s something we want to earn with big public release, and we are not there yet ;)

**Comment by arb** [comment]
I will also take USD as well 😉  If you're interested, email me and we can set something up.

**Comment by gr2m** [comment]
we are a poor open source project with no moneys, I’m afraid ¯\_(ツ)_/¯ but thanks for your help Adam, we’ll figure it out :)

**Comment by arb** [comment]
Alrighty; good luck!

**Comment by lancespeelmon** [comment]
FYI - we just converted to good7 - this diff may help you... https://github.com/lancespeelmon/gooder-bunyan/commit/87ccb856873d742e9bf715d58b24253a8db0e11c 
Best, L
