### ISSUE TITLE
How to include certain properties in the log file?

### ISSUE THREAD

**Issue by sulhome** [hapijs/good#501]
Let's say I want to log the response. I am only interested in response time, status code and Url. How can I log only these information?

Thank you

**Comment by arb** [comment]
You'd want to set your filters to only report "ops" events and use something like "white-out" to strip out the keys you don't want. Check out https://github.com/hapijs/good/blob/master/examples/censoring-with-white-out.md for an example of using white-out to remove keys from reports.

You could also write your own transform stream and handle the filtering and payload mutation yourself and the pipe it to stdout or to a file or where ever you want to log data to.
