### ISSUE TITLE
Subscribe to file rotate events (rotating-file-stream)

### ISSUE THREAD

**Issue by sulhome** [hapijs/good#502]
I am using [rotating-file-stream](https://github.com/iccicci/rotating-file-stream) for file rotation in good. 

how can I subscribe to the events emitted by rotating-file-stream?

Is there a way to get hold of the rotating-file-stream instance so I can subscribe to these events?

thank you

**Comment by arb** [comment]
Not really... not in a way that is documented or supported. What are you trying to do?

**Comment by sulhome** [comment]
I want to send log files to another location (S3 bucket)
so the workflow I want to implement is like this
log to file --> rotated event raised --> send this file to S3 bucket

**Comment by arb** [comment]
You could just log directly to the S3 bucket instead? Or do you really want to have the log file and a copy of it on S3?

**Comment by sulhome** [comment]
you can post files to S3 but not log entries so you can't use http or file

**Comment by arb** [comment]
It would probably be easier and cleaner to use another tool for this; like a cron job or something. 

Alternatively, you could use something like https://github.com/Coggle/s3-streamlogger. Remember, you can use ANY stream with good now; not just the ones under the hapijs GitHub organization.
