### ISSUE TITLE
Update Tests

### ISSUE THREAD

**Issue by arb** [hapijs/good#519]
Now that we support functions again as arguments, use them more often to make tests easier to read and understand.

**Comment by jdcormack** [comment]
I would like to help, can you tell me more?

**Comment by arb** [comment]
Rather than pass strings as modules, just pass function constructors. 

https://github.com/hapijs/good/commit/ae1778ba6f2902bf9d52f497dd3c7db5d07c195e

**Comment by omerbn** [comment]
I would like to help, but didn't understand what exactly do you need.
Can you elaborate?

**Comment by arb** [comment]
In places like https://github.com/hapijs/good/blob/master/test/monitor.js#L145-L151 we pass a string as `module`. Now that you can pass constructor functions as the `module` value, we can update many of these tests to pass functions instead of strings.
