### ISSUE TITLE
Add detection for errrornous reporter pipeline

### ISSUE THREAD

**Issue by yonjah** [hapijs/good#525]
Currently good does not verify if the way streams are defined in the pipeline makes sense.
Some pipelines might fail immediately but some will fail silently after a short period (if they last stream is from Transform type)

Having good verifying the pipeline will not only help users to detect error in their own configuration but will also help catch cases where Stream maintainers actually used the wrong type of stream with their module.

If this is decided as something might worth implementing I can probably look at it and try to submit a PR

**Comment by arb** [comment]
I will take a PR for this as long as it's a simple solution. The code to create the different objects is complicated enough and I don't think this provides much value.
