### ISSUE TITLE
good-logs do not occur when starting my server

### ISSUE THREAD

**Issue by ignivaravinderrikhi** [hapijs/good#527]
I am new to **good**, previously I was simply using console.log to know the control flow of my application, I wanted an automatic logger, don't know if it is one or not. Please excuse me if it is a silly issue,  but I installed **good**, **good-squeez** and **good-console** 

`"good": "7.0.2",
  "good-console": "6.1.2",
  "good-squeeze": "5.0.0"`

the plugin options are 

`
var goodOptions = {
    ops: {
        interval: 1000
    },
    reporters: {
        myConsoleReporter: [{
            module: 'good-squeeze',
            name: 'Squeeze',
            args: [{ log: '*', response: '*', request: '*' }]
        }, {
            module: 'good-console'
        },
        'stdout']
    }
};
`
& registered it like this
`{
        register : require('good'),
        goodOptions
    }`

but when I start my server, I see no logs , Please Help me out, I am a novice to the process

**Comment by Marsup** [comment]
Can you provide a more complete code containing the registration and start of the server ?

**Comment by ignivaravinderrikhi** [comment]
@Marsup Sure 
[good-gist](https://gist.github.com/ignivaravinderrikhi/ef87d6309ace368d3c1fd3fe33c5fa80)

**Comment by arb** [comment]
Are you running this on a VM like docker or something or is this running locally on your machine? Are you sure the server is starting and not erroring out somewhere else?

**Comment by ignivaravinderrikhi** [comment]
I am running this locally and Server is also working fine, as all the routes are performing okay . Is there a possibility of a version mismatch ???

**Comment by arb** [comment]
Are you still having issues here?

**Comment by nicolasiscoding** [comment]
Hey Arb, I am also having this issue. Trying Hapi.js for the first time and this is my attempt at getting logging working:

```
const LoggerOptions = {
  myConsoleReporter: [{
            module: 'good-squeeze',
            name: 'Squeeze',
            args: [{ log: '*', response: '*', request: '*' }]
          },

          {
            module: 'good-console'
          },
          'stdout'
    ]
};

...
...
...

server.register([{
    register: Inert
  }, {
    register: Good,
    LoggerOptions
  }], (err) => {
    if (err) {
      console.error(err);
    }

    server.route(Routes);

    server.start(() => {
          console.info(`Server running at: ${server.info.uri}`);
        });
  });
```

No logging occurs even when I run from straight command line like `node server.js`

**Comment by arb** [comment]
Are you doing anything that should be logged in those routes? Nothing in that code should write to the good logging stream.

**Comment by nicolasiscoding** [comment]
When I hit my standard homepage route (GET on a '/')  I do not see any logging in my console







On Tue, Jan 17, 2017 at 10:42 AM -0500, "Adam Bretz" <notifications@github.com> wrote:












Are you doing anything that should be logged in those routes? Nothing in that code should write to the good logging stream.

**Comment by JulianHi** [comment]
@ignivaravinderrikhi @nicolasiscoding 

i had the same problem... there seems to be an error in the documentation

> & registered it like this
{ register : require('good'), goodOptions }

change to:

> & registered it like this
{ register : require('good'), options: goodOptions }

that solved at least my problem.

**Comment by nicolasiscoding** [comment]
@JulianHi, Thank you so much! The smallest of typos can create the biggest of headaches!

**Comment by arb** [comment]
@ignivaravinderrikhi this issues is several months old with no new comments from you. If you are still having issues, please open a new issue.

**Comment by WebMatrixware** [comment]
This is a non-issue in that the plugin functions correctly, but it is a huge issue that your documentation is still wrong. How are users supposed to user your plugin if you cannot even document how to use it correctly?

**Comment by arb** [comment]
Where is the documentation incorrect?

**Comment by WebMatrixware** [comment]
> @ignivaravinderrikhi @nicolasiscoding

> i had the same problem... there seems to be an error in the documentation

> & registered it like this
> { register : require('good'), goodOptions }
> change to:

> & registered it like this
> { register : require('good'), options: goodOptions }
> that solved at least my problem.

And from the documentation example on the [home page](https://github.com/hapijs/good)...

````
server.register({
    register: require('good'),
    options,
}
````
which does not work, it should be
````
server.register({
    register: require('good'),
    options: options,
}
````

**Comment by arb** [comment]
It works fine using Node 4.x.x which has been stipulated as the minimum version in the good's [package.json](https://github.com/hapijs/good/blob/master/package.json#L15-L17) file. This is object short hand notation and was introduced in Node 4.

**Comment by WebMatrixware** [comment]
I am running node 6.10.1 which is the current stable version and it does not work there. I would also point out that since at least the other two posters in this feed had the same issue this is clearly not an isolated fluke.

**Comment by arb** [comment]
Any PR to help clarify or improve documentation are always welcomed. Thanks for your interest in this project.
