### ISSUE TITLE
Feature Request: Allow logging of custom request parameters

### ISSUE THREAD

**Issue by micahhausler** [hapijs/good#529]
I'd like to use Good to create an audit log on a service, but currently I can only add request parameters that are [predefined and hard-coded](https://github.com/hapijs/good/blob/b8f923eee4e90230cf980a2e5d883a20e3b26738/lib/utils.js#L63-L98) and only the [payload](https://github.com/hapijs/good/blob/b8f923eee4e90230cf980a2e5d883a20e3b26738/lib/utils.js#L96-L98) from the response.

What I'd like to have is a way to get custom user-defined parameters off the request object to inject into the log. It might look something like this on the `RequestSent` class's constructor method:

```javascript
if (reqOptions.extras.len > 0) {
    _.forEach(resOptions.extras, function(value, key) {
        if (request[key]){
            this[key] = request[key]
        }
     });
}
```

That way, I could inject user and group information to each request, say in an extension
```javascript
module.exports = {
    type: "onPostAuth",
    method: function(req, res){
        req.user_id = req.session.user_id;
        req.group_id = req.session.group_id;
        res.continue();
    }
};
```

And then add the parameter names to my logging options

```javascript
const options = {
    includes: {
        "request": [
            "headers",
            {"extras": ["user_id", "group_id"]}
        ]
    },
    reporters: {
        consoleReporter: [{
            "module": "good-console"
        }, 
        "stdout"]
    }
};
```

I'm not asking for a critique of this snippet's implementation, just if a patch with this type of logic would be accepted.

**Comment by arb** [comment]
What about just including `request.state` in the log? You could put your extra stuff in there and then you'd only need small change to `good` to have them show up?

**Comment by micahhausler** [comment]
Thats what I ended up doing. 
```javascript
module.exports = {
    type: "onPostAuth",
    method: function(req, res){
        req.log(["audit"], {user_id: req.session.user_id, ...});
        res.continue();
    }
};
```
and then I could filter on that log tag.
