### ISSUE TITLE
responseTime should not include tail time

### ISSUE THREAD

**Issue by kevinmstephens** [hapijs/good#530]
`responseTime` should represent the difference between request received and response sent. 

Currently, when a tail is used and log event is `tail` then `responseTime` includes the time taken for the tail to complete.

https://github.com/hapijs/good/blob/master/lib/utils.js#L71

Recommend changing to
`this.responseTime = request.info.responded || Date.now() - request.info.received;`

**Comment by arb** [comment]
I'll take a PR.
