### ISSUE TITLE
Stream pipeline error

### ISSUE THREAD

**Issue by gagle** [hapijs/good#544]
What about this?

https://github.com/hapijs/good/blob/master/lib/monitor.js#L129

If the pumpified stream emits an error it silently prints to the console the error. Are there better alternatives like implementing a backoff algorithm and try to recreate the pipline?

**Comment by arb** [comment]
That sounds like adding a ton of complexity for something that won't happen very often. That error handler should only pop if there is a like a node core stream and pipe error.
