### ISSUE TITLE
Support for custom events

### ISSUE THREAD

**Issue by lostthetrail** [hapijs/good#545]
Example:
I have an http client that emits events much like wreck, but includes a bunch of additional features.

Is there a way to support custom events, much like wreck is currently supported, in the library?

**Comment by arb** [comment]
Not at this time. There *IS* a way you could hack it but it's not documented and would require you doing some things you "aren't supposed to do".

**Comment by lostthetrail** [comment]
That sounds like it may be a better option than clone and own of Good... Your thoughts?

**Comment by arb** [comment]
It's unlikely that we'll add support for custom things outside the hapi ecosystem. If you're http client has a handle to a hapi server object, you could just send logs though that, then it would get picked up by good.

The magic that lets wreck logging work is https://github.com/hapijs/good/blob/master/lib/monitor.js#L141-L144. I guess if we really really wanted to add outside things, we would do it similar to that but again, I don't know if there's much value i that approach. If we supported outside things, they would all have to agree to the same interface to work with good and I really doubt we'll be able to make that happen.

**Comment by lostthetrail** [comment]
The plan was to have the http client emit events on a symbol. The events were to contain timing information for both aggregated metrics and specific logging for debugging.

For example: using that timing information to know you have a DNS problem, but also to correlate a single users bad experience with a slow response in creating a socket.

I could just log it out directly or attach the timings to the response object.

**Comment by lostthetrail** [comment]
For now, I have just been using `request.log` to get the support I wanted.
