### ISSUE TITLE
Response even timestamp in based on received time, not responded time

### ISSUE THREAD

**Issue by lbland** [hapijs/good#551]
I do not know if this is by design or a bug, but the RequestSent class sets a timestamp to the request.info.received time.  This causes logs to have events in logical order, but the timestamps will look out of order.  This is used for response events, so it would make more sense to use 
`this.timestamp = Date.now()`
or
`this.timestamp = request.info.responded`

Is there a reason for this that i am missing?

**Comment by lbland** [comment]
#552

**Comment by arb** [comment]
Trumped by #531
