### ISSUE TITLE
Crash when reporter throws an error

### ISSUE THREAD

**Issue by MaaKut** [hapijs/good#565]
I have a Hapi+Good configuration which reports to logstash via good-logstash-tcp. The problem is that whenever logstash instance becomes unavailable, an error is thrown by the reporter which in turn causes Good to crash the Hapi process.

Shouldn't Good handle errors like that? I can hardly imagine a situation where application crash in case of logging failure could be a desired behaviour.

**Comment by arb** [comment]
Yes it should. That's what these lines are for https://github.com/hapijs/good/blob/master/lib/monitor.js#L148-L151

If you can create a simple to reproduce case, I can investigate further.

**Comment by AdriVanHoudt** [comment]
@arb why not throw there?

**Comment by MaaKut** [comment]
> If you can create a simple to reproduce case, I can investigate further.

**Comment by AdriVanHoudt** [comment]
@arb (if you want we can discuss this elsewhere) is there a way to catch that? I'd prefer my server auto reboots so my logging works again then this weird state. What happens with the log stream, does it just voids?

**Comment by arb** [comment]
@MaaKut that's not really a simple server as it relies on modules outside the hapi organization.
@AdriVanHoudt that makes sense, how would we handle that? Pass some kind of optional fail callback?

**Comment by MaaKut** [comment]
@arb The only external module here is `good-logstash-tcp` - it's just a reporter, whose crash brings down the whole server. Do you mean it throws an error in some proper way so that `good` is unable to handle it?

**Comment by AdriVanHoudt** [comment]
@arb either that or an option to tell it to throw, the callback would be cleaner though (so I can log the error still and then throw to crash and restart)
