### ISSUE TITLE
Error: Cannot find module 'good-squeeze'

### ISSUE THREAD

**Issue by benwingz** [hapijs/good#567]
Hey there, I'm trying to use good for HTTPCOMBINED log reporting into my console and when I follow the exemple on the readme I end up with this message:
`Error: Cannot find module 'good-squeeze'`

I installed good with this npm command:
`npm i good --save`

I took a look at good package.json and I did not find any good squeeze dependency
Did I miss something ?

**Comment by arb** [comment]
Yes, you need to add `good-squeeze`. It's not bundled with good and is its own module.

**Comment by benwingz** [comment]
You should document it on your README.md.
Something like:
Run the install: `npm i good good-squeeze good-console`

Anyway thanks for your answer

**Comment by arb** [comment]
I have no way of knowing what modules a user is going to need. You can use any stream module from npm with good.
