### ISSUE TITLE
Adding extra fields to top level of log object

### ISSUE THREAD

**Issue by rossanthony** [hapijs/good#570]
We are using 'good' with 'good-squeeze' and 'SafeJson' for logging and the stdout is being consumed by a logging service called Splunk. We have lots of apps and want to be able to easily filter by an AppID. 

Is it possible to add a custom field via the config of 'good' or maybe 'good-squeeze', so we can insert a static app identifier to the top level of every object logged by good? 

For example:
```
{ 
   appId: 2001,
   event: "request",
   method: "post",
   path: "/test",
   timestamp: 1510788236049,
   ....
}

**Comment by arb** [comment]
You'd have to add another transform stream between before `SafeJson` and attach the value there.

**Comment by rossanthony** [comment]
Thanks @arb, I suspected that might be the only option. Do you know of any good examples showing how to setup a custom transform stream?

**Comment by arb** [comment]
The tests for good would be a good place to start. Not sure outside of that as people seem to create custom transform streams at the application level and not open source.

**Comment by rossanthony** [comment]
Looked at the source for 'good-console' that served as a good starting point. Thanks a lot for your help.
