### ISSUE TITLE
I can't use   good(^7.3.0) vs hapi(^17.2.0)

### ISSUE THREAD

**Issue by nvs2394** [hapijs/good#573]
This is my code
```
plugin: require('good'),
    options: {
      ops: {
        interval: 1000
    },
    reporters: {
        consoleReporter: [{
            module: 'good-squeeze',
            name: 'Squeeze',
            args: [{ log: '*', response: '*' }]
        }, {
            module: 'good-console'
        }, 'stdout']
      }
    }
```
I copy it from docs.  Can you explain for me 
then error:
<img width="1366" alt="screen shot 2017-12-25 at 2 42 03 pm" src="https://user-images.githubusercontent.com/10525781/34335586-86037b96-e982-11e7-83ab-af297f42c062.png">

**Comment by frankthelen** [comment]
That is correct. Hapi 17 goes together with Good 8 which is not yet released. Good 7 works with Hapi 16. Hope that helps.

**Comment by henrikdahl** [comment]
You may simply do `yarn add hapijs/good` to use Good with Hapi 17 ✌️

**Comment by oPauloChaves** [comment]
Thanks @henrikdahl, That works!

**Comment by nvs2394** [comment]
thanks @henrikdahl That works
