### ISSUE TITLE
Is there a way to change the timestamp format to ISO?

### ISSUE THREAD

**Issue by frankthelen** [hapijs/good#577]
Hi!

I have a question (can't find anything it the docs):
Is there a way to change the `timestamp` date format to ISO.

I am using this reporter configuration with Good 8.0.0-rc1.

```
    reporters: {
      stdout: [{
        module: 'good-squeeze',
        name: 'Squeeze',
        args: [{
          log: '*', request: '*', response: '*', error: '*'
        }],
      }, {
        module: 'white-out',
        args: [{
          password: 'censor'
        }]
      }, {
        module: 'good-squeeze',
        name: 'SafeJson',
      }, 'stdout'],
    },
```

Which outputs timestamp in milliseconds like this:
```
{"event":"log","timestamp":1515606782890,"tags":["info"],"data":...,"pid":89579}
```

Thanks.

**Comment by arb** [comment]
Check the good-console [docs](https://github.com/hapijs/good-console#new-goodconsoleconfig). That's what formats the timestamp before sending it to 'stdout'.

**Comment by frankthelen** [comment]
Thanks for your quick answer. If I understand correctly, `good-console` doesn't play together with `good-squeeze/SafeJson`, right. So, if I want to have a JSON-formatted log output with its `timestamp` ISO-formatted, it's doesn't seam to work. Or am I doing something wrong. Thanks.

**Comment by frankthelen** [comment]
Yep. Unfortunately, I didn't find a package that works for me. Anyway, I decided to have some fun and write my own transform stream. Maybe it's also interesting for others. Here it is: https://www.npmjs.com/package/good-map
