### ISSUE TITLE
New Lead Maintainer Requested

### ISSUE THREAD

**Issue by arb** [hapijs/good#589]
I am unable to continue to dedicate time to this module so I'm looking for someone in the community to step up and take over! Please let me know if you're interested.

**Comment by rossanthony** [comment]
Hi @arb, roughly what sort of time commitment do you feel this will require? Are there currently any planned new features on the roadmap, and work-in-progress that would need to be taken over?

**Comment by arb** [comment]
Not really. The last big thing was just porting to node 8. Some people think the configuration is too complicated so maybe some work there down the road.

**Comment by labsvisual** [comment]
Hey @arb, I can take this on.

**Comment by hueniverse** [comment]
@labsvisual thanks for offering to help. The first step is to start working on open issues, submitting PRs and reviewing existing PRs. Once we see how you do, we can discuss adding you as a maintainer.

**Comment by hsitraka** [comment]
@hueniverse, I can take it.

**Comment by hueniverse** [comment]
@hsitraka thanks for offering to help. Same goes - the first step is to start working on open issues, submitting PRs and reviewing existing PRs. Once we see how you do, we can discuss adding you as a maintainer.
