### ISSUE TITLE
Error when trying to filter out a tag using good-squeeze and hapi-good-winston

### ISSUE THREAD

**Issue by mihristov** [hapijs/good#595]
Hi,

I'm trying to filter out a tag using [good-squeeze](https://github.com/hapijs/good-squeeze/), following [this](https://stackoverflow.com/a/45149337/5841981) SO answer, except I'm not using good-console, but [hapi-good-winston](https://github.com/alexandrebodin/hapi-good-winston). Here is what I have in terms of logging configurations: https://pastebin.com/aXChDN7j
The endpoint config has a tags property, just like the SO answer.
When I try to start my app, the following error occurs:
`There was a problem (Error: Cannot pipe, not readable) in consoleReporter and it has been destroyed.`
Although there is an error, the logger seems to work fine and filter out the given endpoint. If I put the goodWinston reporter (line 14) after Squeeze, then the error is gone, but the filtering is not working either.
Do you have any advice? What am I doing wrong and why is this error showing if the reporter seems to be working fine?

versions:
"winston": "3.1.0",
"hapi": "17.5.4"
"good-squeeze": "5.1.0"
"good": "8.1.1"
"hapi-good-winston": "2.0.1"

**Comment by ratsimba** [comment]
I think that good-squeeze can't read the stream returned by `hapi-good-winston` because it is  not readable.
