### ISSUE TITLE
Good event filters not getting applied in log file

### ISSUE THREAD

**Issue by bhawna91** [hapijs/good#605]
I created a new npm package for suppressing response event from the log file. The transform function for the stream in the package is - 
```js
    _transform(data, enc, next) {

        if (data.event === 'response' && data.config.suppressResponseEvent === true) {

            return next();
        }

        return next(null, data);
    } 
```
and is exposed as Filter

This is how I set the suppressResponseEvent config field in server.js file - 
```js
var routeConfig = {
    plugins: {
        good: {
            suppressResponseEvent: true
        }
    }
};
server.route({
    method: "GET",
    path: "/user",
    handler: async (request, h) => {
           .....some code here
	    config: routeConfig
  });
```

In good-options , I am using this filter - 
```js
     fileReporter: [{
            module: 'good-squeeze',
            name: 'Squeeze',
            args: [{ request: '*', response : '*', ops: '*' , log: '*'}]
        }, {
            module: 'good-squeeze',
            name: 'SafeJson'
        },
        {
           module: 'my-custom-package',
           name: 'Filter',
           args: [{ log: '*', response: '*' }]
         },
        {
            module: 'rotating-file-stream',
            args: ['mylog.log',
            {
                size: '50M',
                path: '/log'
            }]
        }
        ]
```
Code runs fine. I was thinking that the response event for the endpoint should not be present in log after these changes, but its still there. The config object is populated properly though in the event. What am I missing?

**Comment by bhawna91** [comment]
@Nargonath any idea?

**Comment by Nargonath** [comment]
@Nargonath Nope sorry, I haven't been using Good lately.

**Comment by bhawna91** [comment]
@arb - data.config is the config passed to the events of /user endpoint . The routeConfig above. I am trying to suppress the response events based on this config by using suppressResponseEvent: true

The response event has the config populated - {event:"response",.......,config:{suppressResponseEvent:true}} and the expectation is that if (data.event === 'response' && data.config.suppressResponseEvent === true){return next();} should be filtering out this event . But it still appears in the log.

**Comment by Nargonath** [comment]
@bhawna91 Please, use markdown syntax for code block otherwise it is really hard to read. You can even use syntax identifier to add syntax highlighting: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by bhawna91** [comment]
done.

**Comment by arb** [comment]
Do you have anything else writing to `'/log'`? What you have there should be working.

**Comment by arb** [comment]
That's likely where the extra log entries are coming from.

**Comment by hsitraka** [comment]
@bhawna91 Is it working?
