### ISSUE TITLE
Question: Problem with filtering events

### ISSUE THREAD

**Issue by opravil-jan** [hapijs/good#606]
Hello,

is it possible to filter reporter to accept only defined events. In old version we used "-" to disable unwanted event, but in current version this does not work. Is it possible to disable/avoid some events to be processed?
I tried these configurations to avoid event ops but non of these worked.

`reporters: {
    console: [
      {
        module: 'good-squeeze',
        name: 'Squeeze',
        args: [{ response: '*', log: '*', error: '*', request: '*' }, { transform }]
      },
      'stdout'
    ]
  }
`
` reporters: {
    console: [
      {
        module: 'good-squeeze',
        name: 'Squeeze',
        args: [{ response: '*', log: '*', error: '*', request: '*', ops: '-' }, { transform }]
      },
      'stdout'
    ]
  }
`

Thank you
Jan Opravil

**Comment by hsitraka** [comment]
Just remove events that you want to disable from `args`. If you need to filter out `ops` event:

reporters: { console: [ { module: 'good-squeeze', name: 'Squeeze', args: [{ response: '*', log: '*', error: '*', request: '*' }, { transform }] }, 'stdout' ] }

**Comment by opravil-jan** [comment]
I found solution. right solution is to use 
```

 if (!Squeeze.filter(this._subscription, data)) {
    return callback(null)
  }
```
