### ISSUE TITLE
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

### ISSUE THREAD

**Issue by Thomas-Loh** [hapijs/good#614]
Hi,
It won't install dependencies when trying to make a Discord bot using the "npm install discord.io winston --save" command and throws the following errors:

npm ERR! file /Users/User/Desktop/Bot/package.json
npm ERR! code EJSONPARSE
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token “ in JSON at position 2 while parsing near '{
npm ERR! JSON.parse “name”: “bot”,
npm ERR! JSON.parse ...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/User/.npm/_logs/2019-05-18T09_56_08_837Z-debug.log

The files are in the proper form and i couldn't find any errors but if u need the files then i'll post them bellow. Thank you.

**Comment by hueniverse** [comment]
This has nothing to do with good.

**Comment by Thomas-Loh** [comment]
whoops accidentally hit return page lol
