### ISSUE TITLE
Question:Ops metrics in Dockerized application

### ISSUE THREAD

**Issue by veerugp** [hapijs/good#619]
good provides the System performances like CPU, disk and other metrics of host system as mentioned [here](https://github.com/hapijs/good/blob/master/API.md#ops). In a dockerized Hapi.js application with good plugin, these metrics does not belong to host system. So, how to interpret these metrics like CPU, disk, memory etc.?

**Comment by Nargonath** [comment]
I'm not a devOps but In containerized application I would think you'd use other tools to monitor your docker container. Each container should have a single responsibility hence I don't think it makes sense to monitor from hapi itself but rather from your docker management system IMO.
