### ISSUE TITLE
Log to file example is broken

### ISSUE THREAD

**Issue by sassrf** [hapijs/good#620]
When I copy-paste [this example](https://github.com/hapijs/good/blob/master/examples/log-to-file.md) into my code, I get the following error:

`[1] "myReporter" at position 1 does not match any of the allowed types`

**Comment by Nargonath** [comment]
Which version of `good` and `hapi` are you using?

**Comment by sassrf** [comment]
`@hapi/hapi": "^18.3.1",`

I have deleted good from my package.json by now, but I simply installed the latest versions on the same day I wrote this issue
